# Generated by Django 4.2.10 on 2026-06-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_loan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ceo_founder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
